name: linting, testing, build
on: 
  push:
    branches: [dev]
    pull_request:
    branches: [dev]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      node-version: [17.x]
  steps: 
  - uses: actions/checkout@v2
  - name: Starting Node.js ${{ matrix.node-version}}
  - uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version}}
  - name: install modules
    run: npm install
  - name: build prod project
    run: npm run build:prod
  - name: change file format
    run: npm run format
  - name: linting
    run: npm run lint
  - name: unit testing
    run: npm run test